# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JkzW0uabNQuCLOAHxDkO-O15dIRitw1t
"""

import streamlit as st
import pandas as pd

# ---------------------------------------------------------
# LOAD DATA
# ---------------------------------------------------------

df = pd.read_csv("data/products_final.csv")  # product_name, benefits, disadvantages, category
sim_df = pd.read_csv("data/similarity_matrix.csv", index_col=0)


# ---------------------------------------------------------
# STREAMLIT UI
# ---------------------------------------------------------

st.title("💄 Beauty Product Insights")
st.write(
    "This app lets you explore beauty products based on customer review insights. "
    "You can view each product’s benefits and disadvantages, and find similar products "
    "using NLP-based similarity scoring."
)

# ---------------------------------------------------------
# SECTION 1: PRODUCT EXPLORER
# ---------------------------------------------------------

st.header("1. Explore Products")

category_choice = st.radio(
    "Choose a product type:",
    ["Moisturizer", "Foundation"]
)

filtered_df = df[df["category"].str.lower() == category_choice.lower()]

product_choice = st.selectbox(
    "Select a product:",
    filtered_df["product_name"].tolist()
)

if product_choice:
    product_row = df[df["product_name"] == product_choice].iloc[0]

    st.subheader("Benefits")
    st.write(product_row["benefits"])

    st.subheader("Disadvantages")
    st.write(product_row["disadvantages"])


# ---------------------------------------------------------
# SECTION 2: SIMILAR PRODUCT FINDER
# ---------------------------------------------------------

st.header("2. Find Similar Products")

compare_choice = st.selectbox(
    "Select a product to find similar ones:",
    df["product_name"].tolist()
)

if compare_choice:
    similarities = sim_df.loc[compare_choice].drop(compare_choice)  # remove itself
    best_match = similarities.idxmax()
    best_score = similarities.max()

    st.subheader("Most Similar Product")
    st.write(f"**{best_match}** (Similarity: {best_score:.2f})")

    # Show details of matched product
    match_row = df[df["product_name"] == best_match].iloc[0]

    st.write("### Why it's similar:")
    st.write("**Benefits:**", match_row["benefits"])
    st.write("**Disadvantages:**", match_row["disadvantages"])
